### ISSUE TITLE
关于readme的SESSDATA问题

### ISSUE THREAD

**Issue by ArenaDruid** [LJason77/bilibili-webhook#12]
readme中提到：
```
……如果没有 SESSDATA，即下载普通的 1080P 视频。
```

但我测试后发现，如果不提供SESSDATA只会下载480p，提供了没有大会员的SESSDATA才能提供1080p。
希望能够调查一下是我的操作有误还是别的什么原因导致这样的情况。

**Comment by LJason77** [comment]
本项目使用了 [yutto](https://github.com/yutto-dev/yutto) 作为下载器，关于清晰度的相关配置也是使用 yutto 的默认值。
如果想要更改清晰度，可以查看 [yutto 的指定视频清晰度等级](https://github.com/yutto-dev/yutto#%E6%8C%87%E5%AE%9A%E8%A7%86%E9%A2%91%E6%B8%85%E6%99%B0%E5%BA%A6%E7%AD%89%E7%BA%A7) 参数，然后在 [config.toml.example](https://github.com/LJason77/bilibili-webhook/blob/master/config.toml.example#L10-L11) 中更改。

**Comment by LJason77** [comment]
测试了一下，我这边不登录的话，B站只有 360P 的清晰度，其他清晰度都是要求登录。
大概是B站本身的限制。

**Comment by ArenaDruid** [comment]
那希望可以修改一下readme的相关表述以避免误导
