### ISSUE TITLE
疑问 / Feature request 如何重新下载某个视频

### ISSUE THREAD

**Issue by quansiji9** [LJason77/bilibili-webhook#15]
订阅的某个列表中的某个视频，如果需要重新下载，是否有除了删掉这个订阅再添加回来之外的重新下载方式?

个人的话遇到这种情况好几次，有整理下载视频不小心删除，有 sessdata 过期导致只下载到 480p 视频。但是没有方便的方法重新下载特定某一个视频。

我有订阅自己的稍后再看，所以我尝试过想把要下载的视频添加到稍后再看，但是估计是下载过这个缓存是跨列表的，并没有重新帮我下载一份。

请问以现在的代码逻辑，有什么办法吗？如果没有，能否计划做一下？例如 config.toml 支持下载单个视频这样的也行

**Comment by LJason77** [comment]
因为我不想重复下载，所以视频是跨列表的，是根据视频的链接来定的。

sessdata 过期的问题，yutto 有强制验证的参数（验证是否登录、验证是否大会员），并且可以参考我的这个回复：https://github.com/yutto-dev/yutto/discussions/180#discussioncomment-7678235 

我这边也有偶尔网络波动导致下载失败需要重新下载的情况，yutto 有批量下载的功能，我是手动批量下载的，并不麻烦。

总之，没有计划做重新下载的功能。

**Comment by quansiji9** [comment]
这个评论我看到了，我也是这么做的，sessdata 确实可以坚持好几个月。

我不方便调用 yutto 是因为是在群晖的 docker 里跑的，要进群晖的 docker 里再去手动下载有那么一点麻烦orz

不过明白了，感谢回答。

**Comment by LJason77** [comment]
链接存在 date.db 里，用 SQLite 打开删除链接可以重新下载。

**Comment by quansiji9** [comment]
搞定了，感谢！ sqlite 格式很简单，在线网站编辑就能删掉想删的记录，这下电脑不开都能搞定了
