### ISSUE TITLE
启动后一直打印日志:  exec /bin/sh: exec format error

### ISSUE THREAD

**Issue by newer-code** [LJason77/bilibili-webhook#6]
启动之后不停重启，日志刷 docker logs bilibili-webhook  
请教下可能是哪里出了问题

**Comment by LJason77** [comment]
`exec format error` 一般是架构问题，比如 32 位设备跑 64 位的程序、arm 跑 x86 等等。

**Comment by newer-code** [comment]
懂了，刚才翻issue的时候看错了，还以为直接拉取下来是amd64的。我的docker宿主机是x86_64，那就是架构问题了。
打扰了
