### ISSUE TITLE
请问如果 SESSDATA 失效了，docker 还能正常下载大会员视频吗？

### ISSUE THREAD

**Issue by TTtrace** [LJason77/bilibili-webhook#8]
我看了一下即使我改了 config 文件夹里的 SESSDATA.txt 文件内容，好像容器内还是会以最开始输入的 sessdata 来访问 b 站？

**Comment by LJason77** [comment]
https://github.com/LJason77/bilibili-webhook/blob/7379164e6b2c90f263211952c06115fcd585c8d8/src/main.rs#L21-L28

创建容器的时候会判断是否存在 `SESSDATA.txt`，如果不存在则将环境变量 `SESSDATA` 写入文件，如果存在则不动文件。

https://github.com/LJason77/bilibili-webhook/blob/7379164e6b2c90f263211952c06115fcd585c8d8/src/update.rs#L76-L82

后续每次下载都是优先读取 `SESSDATA.txt` 的。

也就是说，文件总是优先于环境变量。

如果没有按照预期运行，先确认 SESSDATA 格式是否正确，然后 `SESSDATA.txt` 的路径以及读写权限和所有权。

**Comment by TTtrace** [comment]
好的，我之后再测试一下，我之前好像是因为大会员被冻结了导致登录失败。
